#! /bin/sh
set -e

echo "INSTALL otter ($*)"
TZ=America/Los_Angeles date '+%FT%T.%3N%:z'

case "$1" in
    "prod"|"dev")
        mode=$1
        ;;
    "")
        mode=dev
        ;;
    *)
        echo "Unknown argument $1" >&2
        exit 1
esac

mkdir -p pub/css pub/js pub/ejs pub/html pub/img pub/fonts

### Copy third-party libraries into the pub directory

# All Javascript (.js and .min.js)
cp setup/js/*.js pub/js

# Other
libs=setup/mink-libs
cp -a $libs/bootstrap/css pub
cp -a $libs/bootstrap/fonts pub
cp $libs/animate.min.css pub/css
cp $libs/font-awesome.css pub/css
cp $libs/fullcalendar/fullcalendar/fullcalendar.css pub/css
cp $libs/fullcalendar/fullcalendar/fullcalendar.print.css pub/css
cp $libs/google-buttons/Desktop/2x/44dp/Red-signin-Long-44dp/*.png pub/img
chmod 644 pub/img/Red-signin-*

### Build our own code and copy the result into the pub directory
make -C js $mode-install
cp css/*.css pub/css
cp html/*.html pub/html
cp ejs/*.ejs pub/ejs
cp fonts/* pub/fonts
cp img/* pub/img

### Log info about this installation
if commit=$(git log -1 2>/dev/null); then
    echo "\
Latest commit of the current branch of the local git repository:
$commit"
else
    echo "Missing git info"
fi

echo "Installation complete."
