#! /bin/sh
set -e

case "$1" in
    "prod"|"dev")
        mode=$1
        ;;
    "")
        mode=dev
        ;;
    *)
        echo "Unknown argument $1" >&2
        exit 1
esac

mkdir -p pub/css pub/js pub/ejs pub/html pub/img pub/fonts

### Copy third-party libraries into the pub directory
cp mink-libs/jquery.min.js pub/js
cp mink-libs/can.min.js pub/js
cp mink-libs/sha1.js pub/js
cp -a mink-libs/bootstrap/* pub
cp mink-libs/jquery.timeago.js pub/js
cp mink-libs/autosize-master/jquery.autosize.min.js pub/js
chmod a-x pub/js/jquery.autosize.min.js
cp mink-libs/animate.min.css pub/css
cp mink-libs/font-awesome.css pub/css

# Fullcalendar and dependencies
cp mink-libs/fullcalendar/fullcalendar/fullcalendar.css pub/css
cp mink-libs/fullcalendar/fullcalendar/fullcalendar.print.css pub/css
cp mink-libs/fullcalendar/fullcalendar/fullcalendar.min.js pub/js
cp mink-libs/fullcalendar/lib/moment.min.js pub/js
cp mink-libs/fullcalendar/lib/jquery-ui.custom.min.js pub/js

### Build our own code and copy the result into the pub directory
make -C js $mode-install
cp css/*.css pub/css
cp html/*.html pub/html
cp ejs/*.ejs pub/ejs
cp fonts/* pub/fonts
cp img/* pub/img
