#! /bin/sh
set -e

case "$1" in
    "prod"|"dev")
        mode=$1
        ;;
    "")
        mode=dev
        ;;
    *)
        echo "Unknown argument $1" >&2
        exit 1
esac

mkdir -p pub/css pub/js pub/ejs pub/html pub/img pub/fonts

### Copy third-party libraries into the pub directory

# All Javascript (.js and .min.js)
cp setup/js/*.js pub/js

# Other
libs=setup/mink-libs
cp -a $libs/bootstrap/css pub
cp -a $libs/bootstrap/fonts pub
cp $libs/animate.min.css pub/css
cp $libs/font-awesome.css pub/css
cp $libs/fullcalendar/fullcalendar/fullcalendar.css pub/css
cp $libs/fullcalendar/fullcalendar/fullcalendar.print.css pub/css
cp $libs/bootstrap-timepicker/css/bootstrap-timepicker.min.css pub/css
cp $libs/jquery.timepicker.css pub/css

### Build our own code and copy the result into the pub directory
make -C js $mode-install
cp css/*.css pub/css
cp html/*.html pub/html
cp ejs/*.ejs pub/ejs
cp fonts/* pub/fonts
cp img/* pub/img
