#! /bin/sh
set -e

# Copy public files into a directory structure that we will mirror
# exactly in our S3 bucket used to serve pages for http://esper.com/

# Lists of files to install

html="\
  about-navbar.html \
  contact.html \
  discover.html \
  email-confirmation.html \
  engineer.html \
  faqs.html \
  footer.html \
  index.html \
  intern.html \
  jobs.html \
  nav-menu.html \
  navbar.html \
  payment.html \
  privacy-policy.html \
  redeem.html \
  signup.html \
  splash-navbar.html \
  team.html \
  terms-of-use.html \
  waiting-list.html \
"

css="*.css"
img="*.jpg *.svg *.ico *.png"
js="*.js"

rm -rf pub
mkdir -p pub

# HTML files go to directly under the server root (https://esper.com/...)
# Note that they lose their .html extension, except for index.html.
for x in $html; do
    if [ $x = index.html ]; then
        name=$x
    else
        name=$(basename $x .html)
    fi
    cp html/$x pub/$name
done

# Other files go into /css, /img, /js

mkdir -p pub/css
for x in $css; do
    cp css/$x pub/css
done

mkdir -p pub/img
for x in $img; do
    cp img/$x pub/img
done

mkdir -p pub/js
for x in $js; do
    cp js/$x pub/js
done
