#! /bin/sh
set -e

s3_bucket=esper.com

# Copy the pub/ directory into our S3 bucket used by http://esper.co/
(cd pub && \
    s3cmd put \
      --guess-mime-type \
      --mime-type=text/html \
      --recursive * s3://$s3_bucket )
