#! /bin/sh
set -e

# Get archives from our github repository, then unpack them

if [ ! -d mink-libs ]; then
    git clone git@github.com:timeco/mink-libs.git
fi

cd mink-libs
git checkout master
git pull --ff-only origin master

# mink-libs/jquery
cp jquery-2.0.3.min.js jquery.min.js

# mink-libs/bootstrap
rm -rf bootstrap
unzip bootstrap-3.0.2-dist.zip
mv dist bootstrap

# mink-libs/can
cp can-1.1.8.custom.min.js can.min.js
