#! /bin/sh
set -e

# Normally we are in the setup/ subdirectory of the project
ROOT=$(pwd)
mkdir -p "$ROOT"/bin
mkdir -p "$ROOT"/js

# Get archives from our github repository, then unpack them.
# Prepare two versions of each Javascript file:
# - versionless source, e.g. jquery.js
# - versionless minified code, e.g. jquery.min.js

# Install a source Javascript file, minify it and install the minified version
# as well.
install_js() {
    name="$1"
    src="$2"
    echo "Minifying $name"
    cp "$src" "$ROOT"/js/"$name".js
    uglifyjs -o "$ROOT"/js/"$name".min.js "$src"
}

cd "$ROOT"
if [ ! -d mink-libs ]; then
    git clone git@github.com:esperco/mink-libs.git
fi

cd mink-libs
git checkout master
git pull --ff-only origin master

# jQuery
install_js jquery jquery-2.1.0.js
# full jQuery UI
unzip -o jquery-ui-1.11.0.custom.zip
install_js jqueryui jquery-ui-1.11.0.custom/jquery-ui.js

# Bootstrap
rm -rf bootstrap dist __MACOSX
unzip bootstrap-3.2.0-dist.zip
mv dist bootstrap
install_js bootstrap bootstrap/js/bootstrap.js

# SHA1
install_js sha1 sha1.js

# CanJS
install_js can can-2.0.5.custom.js

# Timeago
install_js jquery.timeago jquery.timeago.js

# Autosize
install_js jquery.autosize autosize-master/jquery.autosize.js

cp font-awesome-4.0.3.css font-awesome.css

# Moment (used by both Fullcalendar and Moment-timezone)
install_js moment moment-2.5.1.js

# Moment-timezone
install_js moment-timezone moment-timezone-0.0.3.js
install_js moment-timezone-data moment-timezone-data-2014-03-19.js

# Fullcalendar and dependencies
rm -rf fullcalendar
unzip fullcalendar-2.1.1.zip
mv fullcalendar-2.1.1 fullcalendar
install_js fullCalendar fullcalendar/fullcalendar.js
# TODO: find out what this custom jquery-ui includes
install_js jquery-ui fullcalendar/lib/jquery-ui.custom.min.js

# jquery-ui: Core + Datepicker
rm -rf jquery-ui-1.10.4.custom
unzip jquery-ui-1.10.4-core-datepicker.zip
install_js jquery-ui-core-datepicker \
  jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.js

# jQuery Timepicker
install_js jquery.timepicker jquery.timepicker-1.3.5-6015cdb4.js

# jsTimezoneDetect (jstz)
install_js jstz jstz-2013-04-01-f9e3e30e.js


# oblivion preprocessor, requires ocaml.
# We install it manually so we don't depend on an opam setup
cd "$ROOT"
if [ ! -d oblivion ]; then
    git clone git@github.com:esperco/oblivion.git
fi
cd oblivion
git checkout master
git pull --ff-only origin master
make
make PREFIX="$ROOT" install

# Don't want my Javascript files to be executable for no reason
chmod a-x "$ROOT"/js/*.js
