#! /bin/sh
set -e

# Normally we are in the setup/ subdirectory of the project
ROOT=$(pwd)

# Get archives from our github repository, then unpack them

cd "$ROOT"
if [ ! -d mink-libs ]; then
    git clone git@github.com:timeco/mink-libs.git
fi

cd mink-libs
git checkout master
git pull --ff-only origin master

# mink-libs/jquery
cp jquery-2.0.3.min.js jquery.min.js

# mink-libs/bootstrap
rm -rf bootstrap
unzip bootstrap-3.0.2-dist.zip
mv dist bootstrap

# mink-libs/can
cp can-1.1.8.custom.min.js can.min.js

cp font-awesome-4.0.3.css font-awesome.css

rm -rf fullcalendar
unzip fullcalendar-2.0.0-beta2.zip
mv fullcalendar-2.0.0-beta2 fullcalendar

# oblivion preprocessor, requires ocaml.
# We install it manually so we don't depend on an opam setup
cd "$ROOT"
if [ ! -d oblivion ]; then
    git clone git@github.com:timeco/oblivion.git
fi
cd oblivion
git checkout master
git pull --ff-only origin master
make
make install
